import Head from 'next/head'
import Image from 'next/image'

import { useQuery, gql } from '@apollo/client';
import Hero from '../components/Hero';

const GET_CARS = gql`
  query GetCar {
    cars {
      data {
        id
        attributes {
          Name
          Description
          Pricing
          Images {
            data {
              attributes {
                url
              }
            }
          }
        }
      }
    }
  }
`;

export default function Home() {

  const { loading, error, data } = useQuery(GET_CARS);

  console.log(data)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </div>
  )
}
